const algorithms = [
  { name: "Adjacent", shape: "PLL", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'", bestTime: null, avgTime: null },
  { name: "Diagonal", shape: "PLL", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'", bestTime: null, avgTime: null },
  { name: "AS1", shape: "Antisune", algorithm: "L' U' L U' L' U2 L", bestTime: null, avgTime: null },
  { name: "AS2", shape: "Antisune", algorithm: "L' U' L U L F' L' F L' U' L U' L' U2 L", bestTime: null, avgTime: null },
  { name: "AS3", shape: "Antisune", algorithm: "F' L F L' U2 L' U2 L", bestTime: null, avgTime: null },
  { name: "AS4", shape: "Antisune", algorithm: "R U2 R' U2 R' F R F'", bestTime: null, avgTime: null },
  { name: "AS5", shape: "Antisune", algorithm: "R' F R F' R U R'", bestTime: null, avgTime: null },
  { name: "AS6", shape: "Antisune", algorithm: "R' U R U' R2 F R F' R U R' U' R", bestTime: null, avgTime: null },
  { name: "H1", shape: "H", algorithm: "R2 U2 R' U2 R2", bestTime: null, avgTime: null },
  { name: "H2", shape: "H", algorithm: "F R2 U' R2 U' R2 U R2 F'", bestTime: null, avgTime: null },
  { name: "H3", shape: "H", algorithm: "R U R' U R U L' U R' U' L", bestTime: null, avgTime: null },
  { name: "H4", shape: "H", algorithm: "x' U2 R U2 R2 F2 R U2 x", bestTime: null, avgTime: null },
  { name: "L1", shape: "L", algorithm: "R' U R' U2 R U' R' U R U' R2", bestTime: null, avgTime: null },
  { name: "L2", shape: "L", algorithm: "R U2 R2 F2 R U R' F2 R F'", bestTime: null, avgTime: null },
  { name: "L3", shape: "L", algorithm: "R U2 R' F' R U2 R' U R' F2 R", bestTime: null, avgTime: null },
  { name: "L4", shape: "L", algorithm: "F R' F' R U R U' R'", bestTime: null, avgTime: null },
  { name: "L5", shape: "L", algorithm: "F R U' R' U' R U R' F'", bestTime: null, avgTime: null },
  { name: "L6", shape: "L", algorithm: "R U2 R2 F R F' R U2 R'", bestTime: null, avgTime: null },
  { name: "P1", shape: "Pi", algorithm: "R U' R2 U R2 U R2 U' R", bestTime: null, avgTime: null },
  { name: "P2", shape: "Pi", algorithm: "R' F2 R F' U2 R U' R' U' F", bestTime: null, avgTime: null },
  { name: "P3", shape: "Pi", algorithm: "F R2 U' R2 U R2 U R2 F'", bestTime: null, avgTime: null },
  { name: "P4", shape: "Pi", algorithm: "R U2 R' U' R U R' U2 R' F R F'", bestTime: null, avgTime: null },
  { name: "P5", shape: "Pi", algorithm: "R U' R' F R' F R U R' F R", bestTime: null, avgTime: null },
  { name: "P6", shape: "Pi", algorithm: "R' U' R' F R F' R U' R' U2 R", bestTime: null, avgTime: null },
  { name: "S1", shape: "Sune", algorithm: "R U R' U R U2 R'", bestTime: null, avgTime: null },
  { name: "S2", shape: "Sune", algorithm: "L' U2 L U2 L F' L' F", bestTime: null, avgTime: null },
  { name: "S3", shape: "Sune", algorithm: "F R' F' R U2 R U2 R'", bestTime: null, avgTime: null },
  { name: "S4", shape: "Sune", algorithm: "R U R' U' R' F R F' R U R' U R U2 R'", bestTime: null, avgTime: null },
  { name: "S5", shape: "Sune", algorithm: "L F' L' F L' U' L", bestTime: null, avgTime: null },
  { name: "S6", shape: "Sune", algorithm: "R U R' U R' F R F' R U2 R'", bestTime: null, avgTime: null },
  { name: "T1", shape: "T", algorithm: "R' U R U2 R2 F' R U' R' F2 R2", bestTime: null, avgTime: null },
  { name: "T2", shape: "T", algorithm: "R' U R U2 R2 F R F' R", bestTime: null, avgTime: null },
  { name: "T3", shape: "T", algorithm: "L' U' L U L F' L' F", bestTime: null, avgTime: null },
  { name: "T4", shape: "T", algorithm: "F R U R' U' R U' R' U' R U R' F'", bestTime: null, avgTime: null },
  { name: "T5", shape: "T", algorithm: "R U R' U' R' F R F'", bestTime: null, avgTime: null },
  { name: "T6", shape: "T", algorithm: "F U' R U2 R' U' F2 R U R'", bestTime: null, avgTime: null },
  { name: "U1", shape: "U", algorithm: "R2 F2 R U R' F R2 U2 R' U' R", bestTime: null, avgTime: null },
  { name: "U2", shape: "U", algorithm: "R U2 R U' R' F R' F2 U' F", bestTime: null, avgTime: null },
  { name: "U3", shape: "U", algorithm: "R' U R' F R F' R U2 R' U R", bestTime: null, avgTime: null },
  { name: "U4", shape: "U", algorithm: "F R' F' R U' R U' R' U2 R U' R'", bestTime: null, avgTime: null },
  { name: "U5", shape: "U", algorithm: "R U' R2 F R F' R U R' U' R U R'", bestTime: null, avgTime: null },
  { name: "U6", shape: "U", algorithm: "F R U R' U' F'", bestTime: null, avgTime: null }
];

export default algorithms;
