const algorithms = [
  { name: "H1", shape: "H", algorithm: "R U R' U R U' R' U R U2 R'", bestTime: null, avgTime: null },
  { name: "H2", shape: "H", algorithm: "F R U' R' U R U2 R' U' R U R' U' F'", bestTime: null, avgTime: null },
  { name: "H3", shape: "H", algorithm: "R U R' U R U L' U R' U' L", bestTime: null, avgTime: null },
  { name: "H4", shape: "H", algorithm: "F R U R' U' R U R' U' R U R' U' F'", bestTime: null, avgTime: null },
  { name: "L1", shape: "L", algorithm: "R' U2 R U R' U' R U R' U' R U R' U R", bestTime: null, avgTime: null },
  { name: "L2", shape: "L", algorithm: "R' U2 R' D' R U2 R' D R2", bestTime: null, avgTime: null },
  { name: "L3", shape: "L", algorithm: "R U2 R D R' U2 R D' R2", bestTime: null, avgTime: null },
  { name: "L4", shape: "L", algorithm: "F R' F' r U R U' r'", bestTime: null, avgTime: null },
  { name: "L5", shape: "L", algorithm: "x R' U R D' R' U' R D", bestTime: null, avgTime: null },
  { name: "L6", shape: "L", algorithm: "R' U' R U R' F' R U R' U' R' F R2", bestTime: null, avgTime: null },
  { name: "P1", shape: "Pi", algorithm: "R U2 R2 U' R2 U' R2 U2 R", bestTime: null, avgTime: null },
  { name: "P2", shape: "Pi", algorithm: "R' F2 R U2 R U2 R' F2 U' R U' R'", bestTime: null, avgTime: null },
  { name: "P3", shape: "Pi", algorithm: "R' U' F' R U R' U' R' F R2 U2 R' U2 R", bestTime: null, avgTime: null },
  { name: "P4", shape: "Pi", algorithm: "R U R' U' R' F R2 U R' U' R U R' U' F'", bestTime: null, avgTime: null },
  { name: "P5", shape: "Pi", algorithm: "R U' L' U R' U L U L' U L", bestTime: null, avgTime: null },
  { name: "P6", shape: "Pi", algorithm: "R2 D' R U R' D R U R U' R' U R U R' U R", bestTime: null, avgTime: null },
  { name: "T1", shape: "T", algorithm: "R U2 R' U' R U' R2 U2 R U R' U R", bestTime: null, avgTime: null },
  { name: "T2", shape: "T", algorithm: "R' U R U2 R' L' U R U' L", bestTime: null, avgTime: null },
  { name: "T3", shape: "T", algorithm: "l' U' L U l F' L' F", bestTime: null, avgTime: null },
  { name: "T4", shape: "T", algorithm: "F R U R' U' R U' R' U' R U R' F'", bestTime: null, avgTime: null },
  { name: "T5", shape: "T", algorithm: "r U R' U' r' F R F'", bestTime: null, avgTime: null },
  { name: "T6", shape: "T", algorithm: "R' U R2 D r' U2 r D' R2 U' R", bestTime: null, avgTime: null },
  { name: "U1", shape: "U", algorithm: "R' U' R U' R' U2 R2 U R' U R U2 R'", bestTime: null, avgTime: null },
  { name: "U2", shape: "U", algorithm: "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", bestTime: null, avgTime: null },
  { name: "U3", shape: "U", algorithm: "R2 D R' U2 R D' R' U2 R'", bestTime: null, avgTime: null },
  { name: "U4", shape: "U", algorithm: "F R U' R' U R U R' U R U' R' F'", bestTime: null, avgTime: null },
  { name: "U5", shape: "U", algorithm: "R2 D' R U2 R' D R U2 R", bestTime: null, avgTime: null },
  { name: "U6", shape: "U", algorithm: "R2 D' R U R' D R U R U' R' U' R", bestTime: null, avgTime: null }
];

export default algorithms;
