const algorithms = [
  { name: "Dot", algorithm: "R U2 R2 F R F' U2 R' F R F'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "r U r' U2 r U2 R' U2 R U' r'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "r' R2 U R' U r U2 r' U M'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "M U' r U2 r' U' R U' R' M'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Square Shape", algorithm: "l' U2 L U L' U l", shape: "Square Shape", bestTime: null, avgTime: null },
  { name: "Square Shape", algorithm: "r U2 R' U' R U' r'", shape: "Square Shape", bestTime: null, avgTime: null },
  { name: "Small Lightning Bolt", algorithm: "r U R' U R U2 r'", shape: "Small Lightning Bolt", bestTime: null, avgTime: null },
  { name: "Small Lightning Bolt", algorithm: "l' U' L U' L' U2 l", shape: "Small Lightning Bolt", bestTime: null, avgTime: null },
  { name: "Fish Shape", algorithm: "R U R' U' R' F R2 U R' U' F'", shape: "Fish Shape", bestTime: null, avgTime: null },
  { name: "Fish Shape", algorithm: "R U R' U R' F R F' R U2 R'", shape: "Fish Shape", bestTime: null, avgTime: null },
  { name: "Small Lightning Bolt", algorithm: "r U R' U R' F R F' R U2 r'", shape: "Small Lightning Bolt", bestTime: null, avgTime: null },
  { name: "Small Lightning Bolt", algorithm: "M' R' U' R U' R' U2 R U' R r'", shape: "Small Lightning Bolt", bestTime: "0.16", avgTime: "0.16" },
  { name: "Knight Move Shape", algorithm: "F U R U' R2 F' R U R U' R'", shape: "Knight Move Shape", bestTime: null, avgTime: null },
  { name: "Knight Move Shape", algorithm: "R' F R U R' F' R F U' F'", shape: "Knight Move Shape", bestTime: null, avgTime: null },
  { name: "Knight Move Shape", algorithm: "l' U' l L' U' L U l' U l", shape: "Knight Move Shape", bestTime: null, avgTime: null },
  { name: "Knight Move Shape", algorithm: "r U r' R U R' U' r U' r'", shape: "Knight Move Shape", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "F R' F' R2 r' U R U' R' U' M'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "r U R' U R U2 r2 U' R U' R' U2 r", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "r' R U R U R' U' M' R' F R F'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Dot", algorithm: "r U R' U' M2 U R U' R' U' M'", shape: "Dot", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "R U2 R' U' R U R' U' R U' R'", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "R U2 R2 U' R2 U' R2 U2 R", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "R2 D' R U2 R' D R U2 R", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "r U R' U' r' F R F'", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "F' r U R' U' r' F R", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "R U2 R' U' R U' R'", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Cross", algorithm: "R U R' U R U2 R'", shape: "Cross", bestTime: null, avgTime: null },
  { name: "Corners Oriented", algorithm: "r U R' U' r' R U R U' R'", shape: "Corners Oriented", bestTime: null, avgTime: null },
  { name: "Awkward Shape", algorithm: "R U R' U' R U' R' F' U' F R U R'", shape: "Awkward Shape", bestTime: null, avgTime: null },
  { name: "Awkward Shape", algorithm: "F R' F R2 U' R' U' R U R' F2", shape: "Awkward Shape", bestTime: null, avgTime: null },
  { name: "P Shape", algorithm: "R' U' F U R U' R' F' R", shape: "P Shape", bestTime: null, avgTime: null },
  { name: "P Shape", algorithm: "L U F' U' L' U L F L'", shape: "P Shape", bestTime: null, avgTime: null },
  { name: "T Shape", algorithm: "R U R' U' R' F R F'", shape: "T Shape", bestTime: null, avgTime: null },
  { name: "C Shape", algorithm: "R U R2 U' R' F R U R U' F'", shape: "C Shape", bestTime: null, avgTime: null },
  { name: "Fish Shape", algorithm: "R U2 R2 F R F' R U2 R'", shape: "Fish Shape", bestTime: null, avgTime: null },
  { name: "W Shape", algorithm: "L' U' L U' L' U L U L F' L' F", shape: "W Shape", bestTime: null, avgTime: null },
  { name: "Fish Shape", algorithm: "F R' F' R U R U' R'", shape: "Fish Shape", bestTime: null, avgTime: null },
  { name: "W Shape", algorithm: "R U R' U R U' R' U' R' F R F'", shape: "W Shape", bestTime: null, avgTime: null },
  { name: "Big Lightning Bolt", algorithm: "L F' L' U' L U F U' L'", shape: "Big Lightning Bolt", bestTime: null, avgTime: null },
  { name: "Big Lightning Bolt", algorithm: "R' F R U R' U' F' U R", shape: "Big Lightning Bolt", bestTime: null, avgTime: null },
  { name: "Awkward Shape", algorithm: "R U R' U R U2 R' F R U R' U' F'", shape: "Awkward Shape", bestTime: null, avgTime: null },
  { name: "Awkward Shape", algorithm: "R' U' R U' R' U2 R F R U R' U' F'", shape: "Awkward Shape", bestTime: null, avgTime: null },
  { name: "P Shape", algorithm: "F' U' L' U L F", shape: "P Shape", bestTime: null, avgTime: null },
  { name: "P Shape", algorithm: "F U R U' R' F'", shape: "P Shape", bestTime: null, avgTime: null },
  { name: "T Shape", algorithm: "F R U R' U' F'", shape: "T Shape", bestTime: null, avgTime: null },
  { name: "C Shape", algorithm: "R' U' R' F R F' U R", shape: "C Shape", bestTime: null, avgTime: null },
  { name: "Small L Shape", algorithm: "R' U' R' F R F' R' F R F' U R", shape: "Small L Shape", bestTime: null, avgTime: null },
  { name: "Small L Shape", algorithm: "F R U R' U' R U R' U' F'", shape: "Small L Shape", bestTime: null, avgTime: null },
  { name: "Small L Shape", algorithm: "r U' r2 U r2 U r2 U' r", shape: "Small L Shape", bestTime: null, avgTime: null },
  { name: "Small L Shape", algorithm: "r' U r2 U' r2 U' r2 U r'", shape: "Small L Shape", bestTime: null, avgTime: null },
  { name: "I Shape", algorithm: "F U R U' R' U R U' R' F'", shape: "I Shape", bestTime: null, avgTime: null },
  { name: "I Shape", algorithm: "R U R' U R U' B U' B' R'", shape: "I Shape", bestTime: null, avgTime: null },
  { name: "Small L Shape", algorithm: "l' U2 L U L' U' L U L' U l", shape: "Small L Shape", bestTime: null, avgTime: null },
  { name: "Small L Shape", algorithm: "r U2 R' U' R U R' U' R U' r'", shape: "Small L Shape", bestTime: null, avgTime: null },
  { name: "I Shape", algorithm: "R' F R U R U' R2 F' R2 U' R' U R U R'", shape: "I Shape", bestTime: null, avgTime: null },
  { name: "I Shape", algorithm: "r' U' r U' R' U R U' R' U R r' U r", shape: "I Shape", bestTime: null, avgTime: null },
  { name: "Corners Oriented", algorithm: "R U R' U' M' U R U' r'", shape: "Corners Oriented", bestTime: null, avgTime: null }
];

export default algorithms;